# Generated by Django 6.0.6 on 2026-06-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoria',
            options={'verbose_name': 'Auditoría', 'verbose_name_plural': 'Auditorías'},
        ),
    ]
