# Generated by Django 6.0.6 on 2026-06-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_vehiculo_tipo_frenos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_frenos',
            field=models.CharField(blank=True, choices=[('Disco delantero y trasero', 'Disco delantero y trasero'), ('Disco delantero / Tambor trasero', 'Disco delantero / Tambor trasero'), ('Tambor delantero y trasero', 'Tambor delantero y trasero'), ('EBD', 'EBD (Electronic Brakeforce Distribution)'), ('BA/BAS', 'BA/BAS (Brake Assist)'), ('No especificado', 'No especificado')], max_length=50, null=True, verbose_name='Tipo de frenos'),
        ),
    ]
