# Generated by Django 6.0.6 on 2026-06-28 15:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio_estandar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio estándar (RD$)')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de entrega')),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha real de entrega')),
                ('diagnostico', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Diagnóstico', 'Diagnóstico'), ('Esperando Aprobación', 'Esperando Aprobación'), ('En Progreso', 'En Progreso'), ('Suspendida', 'Suspendida'), ('Finalizada', 'Finalizada'), ('Entregada', 'Entregada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=25, verbose_name='Estado')),
                ('subtotal_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal repuestos')),
                ('subtotal_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal servicios')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('itbis', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ITBIS (18%)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo unitario (histórico)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.repuesto', verbose_name='Repuesto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.ordentrabajo', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Detalle de repuesto',
                'verbose_name_plural': 'Detalles de repuestos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('metodo', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta')], max_length=15, verbose_name='Método de pago')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.ordentrabajo', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.ordentrabajo', verbose_name='Orden')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordenes.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Detalle de servicio',
                'verbose_name_plural': 'Detalles de servicios',
            },
        ),
    ]
